// <auto-generated />
using ECommerceWebAPI.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240315123127_SeedingProductsTable")]
    partial class SeedingProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceWebAPI.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Product 1",
                            Name = "Product 1",
                            Price = 19432m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Product 2",
                            Name = "Product 2",
                            Price = 4943m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Product 3",
                            Name = "Product 3",
                            Price = 18301m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Product 4",
                            Name = "Product 4",
                            Price = 7872m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Product 5",
                            Name = "Product 5",
                            Price = 3380m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for Product 6",
                            Name = "Product 6",
                            Price = 9226m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for Product 7",
                            Name = "Product 7",
                            Price = 5270m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description for Product 8",
                            Name = "Product 8",
                            Price = 18015m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description for Product 9",
                            Name = "Product 9",
                            Price = 3566m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description for Product 10",
                            Name = "Product 10",
                            Price = 11127m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description for Product 11",
                            Name = "Product 11",
                            Price = 13508m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description for Product 12",
                            Name = "Product 12",
                            Price = 4399m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description for Product 13",
                            Name = "Product 13",
                            Price = 4258m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description for Product 14",
                            Name = "Product 14",
                            Price = 4739m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description for Product 15",
                            Name = "Product 15",
                            Price = 12914m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description for Product 16",
                            Name = "Product 16",
                            Price = 19622m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description for Product 17",
                            Name = "Product 17",
                            Price = 12734m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description for Product 18",
                            Name = "Product 18",
                            Price = 9028m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description for Product 19",
                            Name = "Product 19",
                            Price = 4207m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description for Product 20",
                            Name = "Product 20",
                            Price = 14857m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
